### ISSUE TITLE
Long fasta files (>50 seqs) stop the identification engine

### ISSUE THREAD

**Issue by vanessamata** [lokalmatador123/BOLDigger#15] opened 2022-07-28 13:49 UTC
For fasta files with many sequences, the identification engine stops after 50 or 100 records, and enters a loop in which no data is retrieved. If the name of the fasta file is changed, then it works again for another 50-100 records. We solved the problem by submitting a different fasta file per sequence (or small batch of sequences) and then merging the information at the end, but it would be good that boldigger did that automatically. I believe BOLD is blocking the retrieval of too many records from the same request file?

**Comment by DominikBuchner** [comment] 2022-07-29 13:35
Would you mind uploading this file so I can take a look at this? The name of the file is actually not send to the BOLD Server so I doubt that the filename is causing the issue here.

**Comment by vanessamata** [comment] 2022-07-29 15:53
[Boldigger_test.zip](https://github.com/DominikBuchner/BOLDigger/files/9221427/Boldigger_test.zip)

here it is! we tried running it and it blocked again :(

**Comment by DominikBuchner** [comment] 2022-07-29 19:30
This seems to be a combination of problems that I don't quite get yet. Will work on this though, I'm sure there is a solution.

**Comment by DominikBuchner** [comment] 2022-07-30 11:42
Dear Vanessa, 
first the most important thing: find your results attached to this post.
[BOLDResults_Boldigger_test_part_1.xlsx](https://github.com/DominikBuchner/BOLDigger/files/9226122/BOLDResults_Boldigger_test_part_1.xlsx)

This one was quite tricky to solve because it was caused by multiple problems:

1. Identifying long (> 500 bp) sequences takes way longer than shorter ones. I implemented a timeout rule into BOLDigger to prevent it from waiting forever for an answer from the BOLD servers. In your case, the combination of identifying 50 sequences at once and their length led to this timeout being exceeded in some cases which caused the error in some cases. The solution to this is easy: reduce the query size, to say, 5. 

2. As you may have noticed I recently changed the way BOLDigger saves the results. For all intermediate saves, it now uses HDF format instead of excel which has a lot of advantages (e.g. constant writing time regardless of file size). For large queries the saving of the excel file took longer than the actual query itself, that's why I changed this. The downside of this format is however that with the first writing of the file one has to define the maximum length of strings in each column as well as their datatype. The data type for the "Process ID" column is a string. The problem with your specific file and a query size of 1 was, that the query for the first 2 sequences was fine, but Seq_3 in your file yielded a top 20 hit list with all private hits. Empty values default to an np.nan object when read into a data frame which is of datatype float64 and therefore was incompatible with the file previously generated. That's the reason why changing the filename solved your issue in the first place: A new results file is generated with the new datatype for the "Process ID" column that then leads to the error whenever the column was not empty. This will be fixed with the next update I publish in a few minutes.

3. The reason it took me so long to solve this is that at the moment there are some faulty records in the BOLD database that lead to the identification engine crashing. I can't fix this because it is an internal problem of BOLD which I already contacted about the issue. Luckily non of your sequences trigger this error, but some of my recent queries did, so I was a bit confused on what caused the issue.

However sorry for the delay in fixing this, I hope that now everything is working perfectly again. If not, don't hesitate to mail me, open an issue here or write me via twitter.

best Dominik

**Closed as completed** 2022-07-30 11:53 UTC
Labels: bug

**Comment by vanessamata** [comment] 2022-08-03 15:19
thanks @DominikBuchner ! Problem solved! 👍
