### ISSUE TITLE
BOLD Not Responding: Attempting Retry

### ISSUE THREAD

**Issue by anilorun** [lokalmatador123/BOLDigger#24] opened 2023-02-28 11:26 UTC
Hi, I run the rbcl analysis on BOLDigger with 3 batch size (since it is reported that it should be less than 5). However, I encountered an error with BOLD did not respond! Retrying. How can I solve this issue?

Thanks for your time.
Anil

I added my fasta file if you want to look at it.
[M6_1-2-3_C10r005_twoline.zip](https://github.com/DominikBuchner/BOLDigger/files/10849675/M6_1-2-3_C10r005_twoline.zip)

**Comment by DominikBuchner** [comment] 2023-02-28 12:04
Hi Anil,
does it wait for 5 minutes for the response or does it immediately show the BOLD did not respond? Have you tried lowering the batch size to 1? 
I noticed that BOLD was slow the last few days.

**Comment by anilorun** [comment] 2023-02-28 13:14
Hi Dominik,
Thank you for your quick response. It shows immediately the BOLD did not respond, and I waited  nearly10 minutes and nothing changed. 
I tried lowering the batch size from 5 to 1 after reading your comment but still it does not work.
I tried the same folder for CO1 and it is working but for rbcl I could not handle the problem :/

Best regards,
Anil

**Comment by DominikBuchner** [comment] 2023-02-28 13:47
Dear Anil,
I remember that the ID engine in BOLDigger was broken for rbcl and ITS because NoMatches look different. I will try to fix this in the near future, but it might take some time.

**Comment by pollingmarcel** [comment] 2023-03-27 08:53
Hi @DominikBuchner,

I run into a similar problem with COI, although I am not sure if it is entirely the same. This is the current error message:

requests.exceptions.RetryError: HTTPConnectionPool(host='boldsystems.org', port=80): Max retries exceeded with url: /index.php/IDS_SingleResult?token=marcelpolling_73188FB0-B9C4-4470-8C4F-0852FEDEDCE6 (Caused by ResponseError('too many 500 error responses'))

Could this have to do with my BOLD account..?

Thanks for letting me know!

**Comment by DominikBuchner** [comment] 2023-03-27 08:57
Hi Marcel,
this is a problem caused by faulty records in the BOLD database. If you follow your link provided you'll see that this is an internal misleading BOLD reference:
![image](https://user-images.githubusercontent.com/38790188/227892806-6c858352-510c-4e08-885a-868bd7c381a7.png)

https://boldsystems.org/index.php/IDS_SingleResult?token=marcelpolling_73188FB0-B9C4-4470-8C4F-0852FEDEDCE6

This is caused by a single sequence in your fasta, you can set the query size to 1 and retry until this error appears. Than you sent the respective sequence including the error message to the BOLD helpdesk and they will fix the record. At least that's how I do it. If you search this sequence via the website you'll also get no result.

best Dominik

**Comment by pollingmarcel** [comment] 2023-03-27 09:02
That was quick! thanks!

**Comment by rishikeshkumar360** [comment] 2023-05-25 03:07
Hey Dominik
I am using boldigger for the analysis of my macroinvertebrates DNA metabarcoding data (primer BF2 and BR2). I uploaded Denoise fasta file on boldigger and it is showing this popup window from past 14 hrs. Does it usually take that much time? the file size is 5.1 mb and number of sequences is 10944.

**Comment by rishikeshkumar360** [comment] 2023-05-25 03:18
<img width="406" alt="Screenshot 2023-05-25 at 11 11 21 AM" src="https://github.com/DominikBuchner/BOLDigger/assets/106106444/ef7a85d6-54c2-4d71-865f-98b37f46ac93">

**Comment by DominikBuchner** [comment] 2023-05-25 04:03
Hi,
no this looks like a badly formatted fasta.
1. How do your headers look? Fasta headers have to be shorter than 80 characters to work with BOLD.
2. Is your fasta formatted as fast 2line? Otherwise BOLDigger won't work but I'm planing to fix this in July.
3. Are there irregular characters in your sequences i.e. characters that are not in the IUPAC code?

If you don't mind you can share your fasta here and I'll take a look at it.

10k sequences will be done in a few hours.
best
Dominik

**Comment by rishikeshkumar360** [comment] 2023-05-25 04:32
Hey 
Thank you for the swift reply.

1. Yes,  some headers are larger than 80 characters. How should I make them shorter?
2. I didn't understand "fast2line". So, I will mail you my one file.
3. I don't think that there is an irregular character in my file.
Please have a look into my data and let me know if you have any questions for my sequence.

Thanks and regards

**Comment by DominikBuchner** [comment] 2023-05-25 04:39
You can simply upload your file here :)

**Comment by rishikeshkumar360** [comment] 2023-05-25 05:57
[SB5.txt](https://github.com/DominikBuchner/BOLDigger/files/11561535/SB5.txt)

**Comment by DominikBuchner** [comment] 2023-05-31 05:06
Hi there @rishikeshkumar360,
sorry this took so long have been quite busy the last few days. Your headers are not the problem, but the file was not in fasta-2line format meaninig, that there is always exactly one header and one sequence per line. I converted this, and it should now run fine with BOLDigger. Let me know if you need any further help!

best Dominik

[SB5-line.txt](https://github.com/DominikBuchner/BOLDigger/files/11608812/SB5-line.txt)

**Comment by onurdogan** [comment] 2023-06-16 08:58
Hi Dominik, 

I have received an output in the ".fasta" format from [apscale_gui ](https://github.com/TillMacher/apscale_gui)'s [LULU Filtering ](https://github.com/TillMacher/apscale_gui#lulu-filtering)step and I've attempted to use it in BOLDigger. Unfortunately, BOLD did not respond, despite the file [apscale_OTUs_filtered.fasta.txt](https://github.com/DominikBuchner/BOLDigger/files/11768052/apscale_OTUs_filtered.fasta.txt) (I i just added the first 20 lines) appearing to be in the correct format. 

When I attempted to use another [M2_3_C10r005_twoline_.fasta.txt](https://github.com/DominikBuchner/BOLDigger/files/11768217/M2_3_C10r005_twoline_.fasta.txt) file that with no output from the apscale program, BOLD was functioning properly. 

Is there a point I missed? 
I would appreaciate any insights or opinions you may have regarding this matter.

Onur.

**Comment by DominikBuchner** [comment] 2023-06-16 14:53
Hi Onur,
Maybe a broken record in this file? Can you try to blast the top 50 OTUs
manually via the website and see if all the top 20 hits are loading?

I'm on vacation without my computer until end of July, if the problem
persists I'm happy to fix it.

Best
Dominik

Onur Doğan ***@***.***> schrieb am Fr., 16. Juni 2023, 10:58:

**Comment by onurdogan** [comment] 2023-08-09 07:22
Hi Dominik,
I solved the problem and luckily progressed throughout the downstream analysis with apscale_gui and TaxonTableTools. I guess the problem was due to either existing short sequences (less than 100 bp) or appeared lowercase bases in the fasta.
Thanks for assistance. 
Enjoy your summer vacation.

**Comment by DominikBuchner** [comment] 2024-05-29 17:49
Fixed with boldigger2.

**Closed as completed by DominikBuchner** 2024-05-29 17:49 UTC
Labels: bug
