### ISSUE TITLE
ID description

### ISSUE THREAD

**Issue by SaschaKrenek** [lokalmatador123/BOLDigger#13] opened 2022-07-26 07:08 UTC
Hi Dominik,

I'm working with BOLDigger v.2.0.3 (and boldigger-cline v.1.0.0) and have the issue that the "ID" in the results file starts with the greater-than (">") symbol (inherited from the fasta file description line). The fasta file is generated with Qiime2 and the ">" symbol unfortunately causes an error when using the BOLDigger taxonomy table together with the Qiime2 read table in TaxonTableTools.
So a fix of this issue would be quite helpful to streamline the usage.

Thanks!
Sascha

[BOLDResults_test-dna-sequences_part_1.xlsx](https://github.com/DominikBuchner/BOLDigger/files/9187299/BOLDResults_test-dna-sequences_part_1.xlsx)
[test-dna-sequences.txt](https://github.com/DominikBuchner/BOLDigger/files/9187363/test-dna-sequences.txt)

**Comment by DominikBuchner** [comment] 2022-07-31 10:20
Hi Sascha,
I looked up old BOLDResult files and it seems like I never removed the ">" even though it would seem to be the correct way to me now. I'm hesitant to change it now because of backward compatibility. Are you sure you have old files that did not show this behavior?

**Comment by OndroV** [comment] 2022-07-31 12:34
Hi Dominik and Sascha,

if I understand this correctly, maybe it's a TTT issue.

I can confirm that TTT has always been crashing with "raw" BOLDResults files for me. 
Below is what I always do/check for a smooth TTT analysis:

1. replace ">" for ""
2. replace the numbering format otu1 otu2 otu100   --->   OTU_0001, OTU_0002, OTU_0100  by excel formula ="OTU_"&REPT(0;6-LEN(A2))&RIGHT(A2;LEN(A2)-3)
3. To prevent warnings about binomial taxonomy, replace and " " for "" (e.g. "No Match" ---> "NoMatch")
4. Make a binomial species column: =IF(F2="";"";IF(G2="";"";F2&" "&G2))
5. Sometimes the column names are not accepted (e.g. "IDs" instead of "ID"), sometimes the sheet names (e.g. "BOLDigger hit" instead of "JAMP hit")
6. Optional: Make a new column of full taxonomy =B2&"_"&C2&"_"&D2&"_"&E2&"_"&F2&"_"&G2 and sort alphabetically to check anything that needs correction

Best,
Ondro

**Comment by SaschaKrenek** [comment] 2022-08-01 07:33
Hi Dominik,

I've checked my results files (made with boldigger-cline) back from early 2021 and they don't have the ">" sign. While I cannot remember to have them removed before using TTT (as all sheets of the results file are without the sign), I wouldn't stake my life on it... ;-)

Best,
Sascha

**Comment by DominikBuchner** [comment] 2024-05-29 17:50
Fixed with boldigger2.

**Closed as completed by DominikBuchner** 2024-05-29 17:50 UTC
Labels: bug
