### ISSUE TITLE
Is BOLD blocking BOLDigger

### ISSUE THREAD

**Issue by MonicaRYoung** [lokalmatador123/BOLDigger#25] opened 2023-05-12 13:15 UTC
Hi Dom!

Me and some lab mates have been trying to use BOLDigger this week without much luck, unfortunately. I haven't had any trouble in the past, but now I can't get the program to run without crashing. It always produces the same error: "too many 500 error responses". I assume that this means the connection is timing out - or that BOLD itself is blocking my IP from accessing the ID Engine. I've tried multiple different batch sizes in case the issue is a time-out error related to a too-large batch size. But alas, I get the same error even with a batch size of 1. I have also logged into BOLD and manually submitted ID Engine requests ranging from 1-20 sequences at a time with no issue, so I don't think it's a problem with my firewall or internet connection. I've even tried it from various locations (different networks), different computers, on VPN vs off. None of it works!

All of this to say - are you experiencing the same problems? Do you have any idea what's going on? Perhaps I'm missing something simple!

**Comment by DominikBuchner** [comment] 2023-05-12 13:17
Hi Monica,
It's working for me but might be related to your fasta file. Could you please provide the file that causes you trouble?
best
Dominik

**Comment by MonicaRYoung** [comment] 2023-05-12 13:55
Well.. I think you've solved the problem! I've tested another file and it seems to work fine! Perhaps this particular fasta file has become corrupt or something? If you can see anything wrong with it please let me know - otherwise we will have to try generating it again! (p.s. the file is a fasta - I just changed it to .txt for the sake of being able to upload it here).
[3_Raw_OTU.txt](https://github.com/DominikBuchner/BOLDigger/files/11464758/3_Raw_OTU.txt)

**Comment by DominikBuchner** [comment] 2023-05-12 14:23
Hi Monica, 
at the moment, some of the records in BOLD seem to be broken, causing me a headache...
When you closely inspect the first OTU of your fasta (49) you will notive, that also on the BOLD website you will never get a proper response for this OTU:
![image](https://github.com/DominikBuchner/BOLDigger/assets/38790188/383bd370-6e26-4f0a-b409-326cd94b9109)

If you extract the html that leads to the page where the top 20 hits are fetched you will see this (http://boldsystems.org/index.php/IDS_SingleResult?token=lokal0209_0A88AD18-8832-48D3-8683-8C149AD28F9C):
![image](https://github.com/DominikBuchner/BOLDigger/assets/38790188/e68a992e-ed68-4457-94d7-14a0743d0bea)

Currently there's nothing I can do about this, since this problem is caused by BOLD itself. What I do, is report the sequence to the BOLD team and they will fix the bad entry. What you can do to keep BOLDigger running is:

1. Once you encounter this issue, set the query size to 1.
2. Let BOLDigger run until you find the broken record
3. Report it to the BOLD team and remove it from your fasta
4. Continue using BOLDigger with the modified fasta

This seems to be a more common issue when your file contains more NoMatches. I will see if I can find a solution to fix this, however there's no clean way to disentangle actual downtime of the website and this error message since no interpretebale error code is sent by the website :/

I hope you can work with the workaround until I or BOLD fixed this.

**Comment by MonicaRYoung** [comment] 2023-05-12 17:45
Boy! this is not ideal as we have bulk soil metabarcode data that invariably generates a lot of "no match OTUs". Perhaps if I bug BOLD support enough with all my issues then they will be motivated to solve the problem :)

Thank you for helping me sort this out!

**Comment by MonicaRYoung** [comment] 2023-05-12 17:47
For my own reference - how do you get to the (or find the) html that leads to the page where the top 20 hits are fetched? I'm a bit of a noob and can't seem to find this link when I use the ID Engine on their website.

**Comment by DominikBuchner** [comment] 2023-05-12 19:30
Regarding the workaround: This is only happening every ~ 10.000 OTUs or sth, so it is possible. 

Regarding your question about the HTML, log in to BOLD, and run the ID engine for the sequence(s) of interest:
Right-click on the respective OTU header:
![image](https://github.com/DominikBuchner/BOLDigger/assets/38790188/0121089c-4e1b-40a8-9278-58fcb4fb7d46)

Select "Inspect" (Sorry my Browser in in German), you will see the HTML source code of the page:
![image](https://github.com/DominikBuchner/BOLDigger/assets/38790188/95e41a32-be76-4b92-9254-19f5b6b6fcb2)

In the div of class "ibox-title" you will find a span tag for each sequence you searched, containing the result of your query:
![image](https://github.com/DominikBuchner/BOLDigger/assets/38790188/00c6e24d-cec2-4ddd-91fa-adddfea4e649)

Complete the link by adding boldsystems.org + /index.php/IDS_SingleResult?token=lokal0209_4B6F0F19-C4BC-4F58-9825-A100154778B1, this will lead you to a page only containing the top 20 results:
![image](https://github.com/DominikBuchner/BOLDigger/assets/38790188/dab7040f-5efd-4290-94ae-130243604d95)

And this is the page BOLDigger actually fetches. So I get all the links from the overview page and then collect the data from each individual page. If this page leads to a broken record, it will never load and I think this bug in the BOLD database itself must be fixed.

Hope this is not too confusing :) Have a nice weekend.

**Comment by DominikBuchner** [comment] 2023-05-12 19:32
In addition to that: 
This is usually no issue for regular bulk samples and also NOT for every NoMatch, and it also does not only happen with NoMatches but sometimes also with regular hits. So with the workaround, it might take a day or two longer since you will have to restart it every 10 hours or sth, but it's still doable! Let me know if you need any further help.

I just realised, when looking at the error code, that I might be able to fix this. Or the BOLD team simply needs an if statement that whenever a call to a non-object is done, they report a NoMatch or sth. Will figure this out latest in July!

**Comment by MonicaRYoung** [comment] 2023-05-12 20:04
Thank you so much for walking me through this step! We will try the workaround for now and see how cumbersome it is :)
Otherwise we're just using BLAST until it's solved lol

**Comment by filipamsmartins** [comment] 2023-05-13 13:52
Dear @DominikBuchner and @MonicaRYoung I had a similar problem in the past (in my case it kept saying that BOLD was not responding) and I solved it by cleaning the fasta headers. Not sure if it is because of the ";" but after removing all the annotations and keeping only the sequence name it has been working fine for me. 
I hope this helps! cheers,
Filipa

**Comment by DominikBuchner** [comment] 2023-05-14 04:48
Thanks Filipa, this is another issue: BOLD does not accept headers longer than 80 bp, I will add this to the "check fasta" function.

**Comment by DominikBuchner** [comment] 2024-05-29 17:48
FINALLY fixed with BOLDigger2.

**Closed as completed by DominikBuchner** 2024-05-29 17:48 UTC
Labels: bug
